dist: xenial

language: node_js

addons:
  apt:
    packages:
      - chromium-browser

node_js:
  - lts/*
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn lint
  - yarn audit
  - yarn test --code-coverage
  - yarn build --prod

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
